apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/microservicio-default: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: proyecto_go
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_USER
              value: usuariodb
          image: mariadb:10.6
          name: db
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-claim0
            # CAMBIO AQUÍ: Cambiamos el nombre del volumen para el script
            - mountPath: /docker-entrypoint-initdb.d
              name: db-init-script-volume
      restartPolicy: Always
      volumes:
        - name: db-claim0
          persistentVolumeClaim:
            claimName: db-claim0
        # CAMBIO AQUÍ: Reemplazamos PVC por ConfigMap
        - name: db-init-script-volume
          configMap:
            name: db-init-script
status: {}